version: '3.8'

services:
  springboot-app:
    build: .
    container_name: srivenkataramana-app
    ports:
      - "8098:8098"
    volumes:
      - E:/data:/data         # ⬅️ Mount Windows E:\data to /data in container
    restart: always
