version: '3.8'

services:
  springboot-app:
    build: .
    container_name: srivenkataramana-app
    ports:
      - "8098:8098"
    volumes:
      - E:/data:/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
